letran/applications/home/urls.py
from django.urls import path

from . import views

app_name = "home_app"

urlpatterns = [

    path(
        '', 
        views.probando.as_view(),
        name='publico',
    ),
    #----------Servicios------------------
    path(
        'mensajeria-documentos/', 
        views.mesa_docu.as_view(),
        name='mensajeria-documentos',
    ),
    
    path(
        'paqueteo/', 
        views.Paqueteo.as_view(),
        name='paqueteo',
    ),
    
    path(
        'servicios-adicionales/', 
        views.Servicios_adicionales.as_view(),
        name='servicios-adicionales',
    ),
    #----------------------------------------
     path(
        'terminos-condiciones/', 
        views.Terminos_cond.as_view(),
        name='terminos-condiciones',
    ),

    path(
        'documentacion-masiva/', 
        views.Docu_masiva.as_view(),
        name='documentacion-masiva',
    ),
    
    path(
        'politica-t-datos/', 
        views.politica_t_datos.as_view(),
        name='politica-t-datos',
    ),
    path(
        'sedes/', 
        views.Sedes.as_view(),
        name='sedes',
    ),
    
    path(
        'quienes-somos/', 
        views.Quienes_somos.as_view(),
        name='quienes-somos',
    ),
    
    path(
        'politica-sgc/', 
        views.Politica_SGC.as_view(),
        name='politica-sgc',
    ),
    
    path(
        'cumplimiento/', 
        views.Cumplimiento.as_view(),
        name='cumplimiento',
    ),
]

letran/applications/pqr/urls.py
from django.urls import path
from . import views
app_name = "pqr_app"

urlpatterns = [
    path(
        'pqr-letran/',
         views.PqrCreateView.as_view(),
         name='pqr',
    ),
    
    path(
        'contacto-letran/',
         views.ContactoCreateView.as_view(),
         name='contacto-letran',
    ),

    
    ]

letran/letran/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.pqr.urls')),
]

letran/applications/home/models.py
from django.db import models

# Create your models here.

letran/applications/pqr/models.py
from distutils.text_file import TextFile
import email
from pyexpat import model
from typing import Text
from django.db import models
# from applications.cliente.models import Departamento

# Create your models here.

class Pqr(models.Model):

    TIPOS = (
        ('C', 'CC'),
        ('CE', 'CE'),
    )
    # ciudad_radi = models.ForeignKey(
    #     Departamento, 
    #     on_delete=models.CASCADE,
    #     verbose_name='Ciudad radicado'
    #     )
    fecha = models.DateField()
    # tipo_pqr 
    # tipo_soli
    otro_cual = models.CharField(max_length=30)
    tipo_do = models.CharField(
        max_length=4,
        choices=TIPOS,)
    n_documento = models.CharField(max_length=12)
    apellidos = models.CharField(max_length=60)
    nombre = models.CharField(max_length=70)
    email = models.EmailField()
    n_contacto = models.CharField(max_length = 10)
    direccion = models.CharField(max_length=120)
    # ciudad_env = models.ForeignKey(
    #     Departamento, 
    #     on_delete=models.CASCADE,
    #     verbose_name='Ciudad envio'
    #     )
    n_guia = models.IntegerField()
    desc_pqr = models.TextField()

class Contacto(models.Model):
    nombre = models.CharField(max_length=40)
    mail = models.EmailField()
    ciudad = models.CharField(max_length=40)
    empresa = models.CharField(max_length=60)
    telefono = models.CharField(max_length=15)
    aceptar = models.BooleanField()

letran/applications/home/views.py
from re import template
from django.shortcuts import render
from django.views.generic import TemplateView

class probando(TemplateView):
    template_name = "publico/index.html"

#-----------Servicios---------------------------------
class mesa_docu(TemplateView):
    template_name = "publico/servicios/mensajeria_documentos.html"

class Paqueteo(TemplateView):
    template_name = "publico/servicios/paqueteo.html"

class Servicios_adicionales(TemplateView):
    template_name = "publico/servicios/serv_adi.html"

#-------------------------------------------------------    

class Terminos_cond(TemplateView):
    template_name = "publico/terminos_condi.html"

class Docu_masiva(TemplateView):
    template_name = "publico/docu_masiva.html"

class politica_priva(TemplateView):
    template_name = "publico/polica_priva.html"

class politica_t_datos(TemplateView):
    template_name = "publico/general/polica_t_datos.html"

class Sedes(TemplateView):
    template_name = "publico/general/sedes.html"

class Quienes_somos(TemplateView):
    template_name = "publico/general/quienes-somos.html"

class Politica_SGC(TemplateView):
    template_name = "publico/politica_sgc.html"

class Cumplimiento(TemplateView):
    template_name = "publico/requerimientos/cumplimiento.html"

letran/applications/pqr/views.py
from dataclasses import field
from re import template
from django.shortcuts import render
from django.views.generic import CreateView
from . models import Pqr, Contacto

class PqrCreateView(CreateView):
    model = Pqr
    template_name = "publico/formulario/pqr.html"
    fields = ['fecha', 'tipo_do', 'n_documento','apellidos', 'nombre','email', 'n_contacto', 'direccion', 'n_guia','desc_pqr']
    success_url = '.'   

class ContactoCreateView(CreateView):
    template_name = "publico/formulario/contacto.html"
    model = Contacto
    fields = ['nombre', 'mail', 'ciudad', 'empresa', 'telefono', 'aceptar']
    success_url = '.'   

letran/templates/publico.html
{% extends "base.html" %} 

{% load static %}

{% block content %}

  <div class="title-bar" data-responsive-toggle="responsive-menu" data-hide-for="medium">
    <button class="menu-icon" type="button" data-toggle="responsive-menu"></button>
    <div class="title-bar-title">Menu</div>
  </div>
  
  <div class="top-bar" id="responsive-menu">
    <a href="{% url 'home_app:publico' %}"> <img src="{% static 'img/colores letran +.png' %}"  alt="10" width="145"> </a>
      <div class="top-bar-right">
        <ul class="dropdown menu" data-dropdown-menu>

          

          <li class="has-submenu">
            <a href="{% url 'home_app:quienes-somos' %}"><strong>Nuestra empresa</strong> </a>
          </li>
        
          <li class="has-submenu">
            <a href="#0"><strong>Servicios</strong> </a>
              <ul class="submenu menu vertical" data-submenu>
                <li><a href="{% url 'home_app:mensajeria-documentos' %}">Mensajeria expresa</a></li>
                <li><a href="{% url 'home_app:paqueteo' %}">Cargue paqueteo</a></li>
                <li><a href="{% url 'home_app:servicios-adicionales' %}">Servicios adicionales</a></li>
                <li><a href="{% static 'img/Tarifarios.pdf' %}">Tarifas</a></li>
            </ul>      
        </li>
        <li class="has-submenu">
          <a href="https://express.firstsource.net.co/"><strong>Cotizar</strong> </a>
        </li>
        
        
        
        <li class="has-submenu">
          <a href="{% url 'home_app:sedes' %}"><strong>Sedes</strong> </a>
        </li>

        <li class="has-submenu">
          <a href="#0"><strong>Ingresar</strong> </a>
          <ul class="submenu menu vertical" data-submenu>
            <li><a href="https://firstsource.appsiscore.com/app/app-cliente/">Express y paqueteo</a></li>
            <li><a href="https://190.24.11.51/openc3/">Financiero</a></li>
          </ul>
        </li>
        <li class="menu-button" role="none">
          <div class="reveal" id="exampleModal1" data-reveal>
          <p class="text-center"><iframe src="https://express.firstsource.net.co/tk1/" width="500"></iframe></p>
        </div>
      </div>
  </div>
 
                        {% block publico-content %}
                        {% endblock publico-content %}
                        

              <footer class="marketing-site-footer">
                          
                  <article class="grid-container">
                          <div class="grid-x grid-margin-x">
                              <div class="medium-6 cell small-order-2 medium-order-1">
                                <h4>Centro de ayuda</h4>
                                <li><a href="{% url 'home_app:cumplimiento' %}">Cumplimiento</a></li>
                                <li><a href="{% url 'pqr_app:pqr' %}">PQR´s</a></li>
                                <li><a href="{% url 'pqr_app:contacto-letran' %}">Contacto</a></li>
                                <li><a href="https://www.computrabajo.com.co/empresas/ofertas-de-trabajo-de-firstsource-sas--9034974DB9E805BA">Trabaje con nosotros</a></li>
                              </div>
                              
                              
                                <div class="medium-6 cell small-order-1 medium-order-2">
                                  <br>
                                  <img class="thumbnail" src="{% static 'img/LETRAN NEGRO.PNG' %} " width="250">
                                </div>
                                
                          </div>
       
                  </article>
                          <div class="marketing-site-footer-bottom">
                            <div class="row large-unstack align-middle">
                              <p class="text-center">© Letran, 2022.</p>
                                <ul class="menu marketing-site-footer-bottom-links">
                                  <li ><a href="{% url 'home_app:politica-t-datos' %}">Politica de privacidad</a></li>
                                  <li><a href="{% url 'home_app:terminos-condiciones' %}">Terminos y condiciones</a></li>
                                  <img src="{% static 'img/MINITIC.png' %}" alt="20" width="110">
                                  <img src="{% static 'img/MINTRANSPORTE.png' %}" alt="20" width="110">
                                </ul>
                              </div>
                            </div>
                </footer>

 
  {% endblock content %}

letran/templates/publico/base_publico.html
{% extends "publico.html" %} 

{% load static %} 

{% block css %} 

{% endblock css %} 

{% block js %} 

{% endblock js %}

letran/templates/publico/general/quienes-somos.html
{% extends "publico/base_publico.html" %} 

{% load static %}

{% block publico-content %}

<div class="orbit" role="region" aria-label="Favorite Space Pictures" data-orbit>
  <div class="orbit-wrapper">
    <div class="orbit-controls">
      <button class="orbit-previous"><span class="show-for-sr">Previous Slide</span>&#9664;&#xFE0E;</button>
      <button class="orbit-next"><span class="show-for-sr">Next Slide</span>&#9654;&#xFE0E;</button>
    </div>
    <ul class="orbit-container">
      <li class="is-active orbit-slide">
        <figure class="orbit-figure">
          <img class="orbit-image" src="{% static 'img/NOSTROS_1_.png' %}" alt="Space">
          
        </figure>
      </li>
      <li class="orbit-slide">
        <figure class="orbit-figure">
          <img class="orbit-image" src="{% static 'img/NOSTROS_2.png' %}" alt="Space">
          
        </figure>
      </li>
      <li class="orbit-slide">
        <figure class="orbit-figure">
          <img class="orbit-image" src="{% static 'img/NOSTROS_3.png' %}" alt="Space">
         
        </figure>
      </li>
      <li class="orbit-slide">
        <figure class="orbit-figure">
          <img class="orbit-image" src="{% static 'img/NOSTROS_4.png' %}" alt="Space">
          
        </figure>
      </li>
    </ul>
  </div>
  <nav class="orbit-bullets">
    <button class="is-active" data-slide="0">
      <span class="show-for-sr">First slide details.</span>
      <span class="show-for-sr" data-slide-active-label>Current Slide</span>
    </button>
    <button data-slide="1"><span class="show-for-sr">Second slide details.</span></button>
    <button data-slide="2"><span class="show-for-sr">Third slide details.</span></button>
    <button data-slide="3"><span class="show-for-sr">Fourth slide details.</span></button>
  </nav>
</div>

  <ul class="tabs" data-responsive-accordion-tabs="tabs medium-accordion large-tabs" id="example-tabs">
    <li class="tabs-title is-active"><a href="#panel1" aria-selected="true">Misión y visión</a></li>
    <li class="tabs-title"><a href="#panel2">Política integral</a></li>
    <li class="tabs-title"><a href="#panel3">Política de seguridad vial</a></li>
    <li class="tabs-title"><a href="#panel4">Certificaciones - Agremiaciones</a></li>
  </ul>

  <div class="tabs-content" data-tabs-content="example-tabs">
    <div class="tabs-panel is-active" id="panel1">
      <article class="grid-container">
        <div class="grid-x grid-margin-x">
          <div class="medium-6 cell small-order-2 medium-order-1">
            <h3>Misión</h3>
                <p class="subheader">Brindar soluciones logísticas adaptadas a las necesidades de cada uno de nuestros clientes; con estándares de calidad, rentabilidad y sostenibilidad por medio de la administración de los procesos, tecnología y personal altamente capacitado; generando el cumplimiento de la promesa de valor y valor agregado a nuestros aliados.</p>
                <h3>Visión</h3>
                <p class="subheader">Para el año 2025 Firstsource bajo su marca Le-Tran busca ser una empresa innovadora y líder en la operación de logística integral a través de procesos estratégicos de alto nivel, orientados al excelente servicio y experiencia especializada al cliente.</p>
                <h3>Valores Corporativos</h3>
                <p class="subheader">
                  La compañía FIRSTSOURCE SAS busca la excelencia de su servicio al cliente a través de los siguientes valores corporativos:
                </p>
            </div>
            <div class="medium-6 cell small-order-1 medium-order-2">
              <img class="thumbnail" src="{% static 'img/DSC_0106.JPG' %}">
          </div>
        </div>
        <div class="grid-x grid-margin-x">
          <div class="medium-4 cell">
            <li class="subheader">Respeto</li>
            <li class="subheader">Honestidad</li>
            <li class="subheader">Compromiso</li>
          </div>
          <div class="medium-4 cell">
            <li class="subheader">Confidencialidad</li>
            <li class="subheader">Excelencia</li>
            <li class="subheader"> Trabajo en equipo</li>
          </div>
        <div class="medium-4 cell">
    
            <li class="subheader">Flexibilidad</li>
            <li class="subheader">Liderazgo</li>
            <li class="subheader">Orientación al cliente</li> 
        </div>
    
    </article>
      
    </div>
    <div class="tabs-panel" id="panel2">
      <article class="grid-container">
        <div class="grid-x grid-margin-x">
          <div class="medium-6 cell small-order-2 medium-order-1">
           <h3>Política de SGI</h3>
            <p class="subheader">FIRSTSOURCE S.A.S mediante el Sistema de Gestión Integrado (SGI), entrega soluciones logísticas enfocadas en el cumplimiento del servicio a traves de las políticas trabajadas en el Sistema de Gestión de Calidad (SGC), el Sistema de Gestión de Seguridad y Salud en el Trabajo(SG-SST) y el Plan de Seguridad Vial (PESV).
              
              </p>
              
              <li><a href="{% url 'home_app:politica-sgc' %}" ><FONT COLOR="navy">Sistema de Gestión de Calidad (SGC) </FONT></a> </li>
              <li><a href="{% url 'home_app:politica-sgc' %}" ><FONT COLOR="navy">Sistema de Gestión de Seguridad y Salud en el Trabajo (SG-SST) </FONT></a> </li>
              <li><a href="{% url 'home_app:politica-sgc' %}" ><FONT COLOR="navy">PCI-DSS</FONT></a> </li>
            
          </div>
          <div class="medium-6 cell small-order-1 medium-order-2">
            <img class="thumbnail" src="{% static 'img/45.jpeg' %}">
          </div>
        </div>
      
      </article>
      
    </div>
    <div class="tabs-panel" id="panel3">

      <article class="grid-container">
        <div class="grid-x align-center">
          <div class="cell medium-8">
            <div class="blog-post">
              
              
              <p >FIRSTSOURCE S.A.S., consciente de la importancia de la seguridad durante las operaciones de transporte, mantendrá niveles de desempeño en seguridad vial durante el desarrollo de estas, sobre condiciones de vehículos, conductores y demás aspectos relacionados con la operación. Para la compañía., es fundamental promover y mantener prácticas de prevención en riesgos viales, por esto establece su compromiso gerencial implementado el Plan Estratégico de Seguridad Vial y asignando los recursos con el fin de mantener un proceso de mejora continua para minimizar los riesgos de ocurrencia de accidentes de tránsito. Para dar cumplimiento a esta política FISRTSOURCE SAS., se basa en: 
                <li>	Desarrollar actividades de promoción y prevención de accidentes en áreas operativas, en las instalaciones de la empresa y las vías públicas, por ello todos los empleados y contratistas son responsables de participar en las actividades que desarrolla la empresa a fin de evitar la ocurrencia de accidentes viales </li>
                <li>	Cumplir con los objetivos y metas del Plan Estratégico de Seguridad Vial. </li>
                <li>	Cumplir con la reglamentación establecida en el Código Nacional de Tránsito terrestre Ley 769 del 2002 y todas aquellas que se adhieran para la prevención en materia de seguridad vial. </li>
                <li>	Vigilar las responsabilidades propias y de nuestros contratistas en cuanto a mantenimiento preventivo y correctivo, procurando óptimas condiciones de operación a los vehículos. </li>
                <li>	Establecer estrategias de concientización tanto para peatones, pasajeros y conductores hacia el respeto de las normas y señales de tránsito. </li>
                <li>	Contar con personal calificado para operar los vehículos. </li>
                <li>	Todos los conductores y operadores que están al servicio de la empresa deben tener un entrenamiento previo en las políticas de salud, seguridad y medio ambiente. </li>
                <li>	Es obligación de los operadores de vehículos, dar cabal cumplimiento a todas las normas legal vigentes en el territorio nacional, en lo que respecta a transito nacional terrestre automotor, transporté y seguridad vial al igual que portar todos los documentos que la normatividad imponga. </li>
                <li>	Divulgación de la política mediante inducción y reinducción. </li>
                Esta política es enfática en la abstención de conducir en estado de embriaguez o de cansancio; no exceder los límites de velocidad, el uso obligatorio del cinturón de seguridad y de los EPP aplicables en la operación y la prohibición en el uso y manipulación de equipos móviles mientras está el vehículo en marcha. 
                
                Es obligación de los colaboradores dar cumplimiento a todas las normas aplicables en seguridad vial y participar en las actividades que desarrolle la empresa, a fin de disminuir la probabilidad de ocurrencia de accidentes, que puedan afectar la integridad física, mental y social de los colaboradores, contratistas, comunidad en general, la propiedad privada, equipos y el ambiente.
                </p>
              <div class="callout">
                <ul class="menu simple">
                  <li><a href="#">Author: Mike Mikers</a></li>
                  <li><a href="#">Comments: 3</a></li>
                </ul>
              </div>
            </div>
          </div>
      
        
        </div></article>

      
      
    </div>
    <div class="tabs-panel" id="panel4">
      <article class="grid-container">
        <div class="grid-x grid-margin-x">
          <div class="medium-6 cell small-order-2 medium-order-1">
           <h4>AGREMIACION FENALCO</h4>
            <p class="subheader">FIRSTSOURCE S.A.S bajo su marca Le-Tran pertenece a la agremiación de mensajeria expresa de la FEDERACIÓN NACIONAL DE COMERCIANTES - FENALCO
              siendo participe de las mesas de trabajo, formación del sector y representación. 
              
              </p>
              <!-- <li><a href="{% url 'home_app:politica-sgc' %}" ><FONT COLOR="navy">Sistema de Gestión de Calidad (SGC) </FONT></a> </li>
              <li><a href="{% url 'home_app:politica-sgc' %}" ><FONT COLOR="navy">Sistema de Gestión de Seguridad y Salud en el Trabajo (SG-SST) </FONT></a> </li>
              <li><a href="{% url 'home_app:politica-sgc' %}" ><FONT COLOR="navy">PCI-DSS</FONT></a> </li> -->
            
          </div>
          <div class="medium-6 cell small-order-1 medium-order-2">
          <center>  <a href="https://www.fenalco.com.co"> <img class="thumbnail" src="{% static 'img/FENALCO.jpg' %}" width="150" alt="50" ></a></center>
          </div>
          <div class="medium-6 cell small-order-2 medium-order-1">
            <h4>CERTIFICACIÓN PCI-DSS</h4>
             <p class="subheader">Actualmente la compañia se encuentra certificada bajo el estándar de seguridad de datos para la industria de tarjeta de pago dando cuplimiento a los requisitos de la norma PCI-DSS 
               
               </p>
               <!-- <li><a href="{% url 'home_app:politica-sgc' %}" ><FONT COLOR="navy">Certificado PCI </FONT></a> </li> -->
               
           </div>
           <div class="medium-6 cell small-order-1 medium-order-2">
            <center> <a href="{% static 'img/documentos/FIRCO22092021 (3).pdf' %}"> <img class="thumbnail" src="{% static 'img/LogoC-Grande.png' %}" width="150" alt="50" ></a> </center>
           </div>
        </div>
      
      </article>
      
    </div>
    <div class="tabs-panel" id="panel5">
      <p>five</p>
      <p>Check me out! I'm a super cool Tab panel with text content!</p>
    </div>
    <div class="tabs-panel" id="panel6">
      <p>six</p>
      <img class="thumbnail" src="assets/img/generic/rectangle-8.jpg">
    </div>
  </div>
    
  


<div class="news-image-gallery-container">
  <div class="row">
    <div class="small-6 medium-6 large-1 columns">
      <div class="orbit" role="region" aria-label="Favorite Space Pictures" data-orbit data-options="animInFromLeft:fade-in; animInFromRight:fade-in; animOutToLeft:fade-out; animOutToRight:fade-out;">
        <ul class="orbit-container">
          <button class="orbit-previous"><span class="show-for-sr">Previous Slide</span>&#9664;&#xFE0E;</button>
          <button class="orbit-next"><span class="show-for-sr">Next Slide</span>&#9654;&#xFE0E;</button>
          <li class="is-active orbit-slide">
            <img class="orbit-image" src="{% static 'img/CLIENTES 1.png' %}" alt="12">
            
          </li>
          <li class="is-active orbit-slide">
              <img class="orbit-image" src="{% static 'img/CLIENTESs 2.png' %}" alt="12">
            </li>
        </ul>
        
        <nav class="orbit-bullets">
          <button class="is-active" data-slide="0"><span class="show-for-sr">First slide details.</span><span class="show-for-sr">Current Slide</span></button>
          <button data-slide="1"><span class="show-for-sr">Second slide details.</span></button>
          <button data-slide="2"><span class="show-for-sr">Third slide details.</span></button>
          
        </nav>
      </div>
    </div>
  </div>
</div>


    
  
  


{% endblock publico-content %}

letran/templates/publico/index.html
{% extends "publico/base_publico.html" %} 

{% load static %}

{% block publico-content %}


<div class="news-image-gallery-container">
  <div class="row">
    <div class="small-12 medium-12 large-8 columns">
      <div class="orbit" role="region" aria-label="Favorite Space Pictures" data-orbit data-options="animInFromLeft:fade-in; animInFromRight:fade-in; animOutToLeft:fade-out; animOutToRight:fade-out;">
        <ul class="orbit-container">
          <button class="orbit-previous"><span class="show-for-sr">Previous Slide</span>&#9664;&#xFE0E;</button>
          <button class="orbit-next"><span class="show-for-sr">Next Slide</span>&#9654;&#xFE0E;</button>

          <li class="orbit-slide">
            <img class="orbit-image" src="{% static 'img/BANNER 6.png' %}" alt="Space">
          </li>

          <li class="orbit-slide">
            <img class="orbit-image" src="{% static 'img/BANNER_1.png' %}" alt="Space">
          </li>
          
          <li class="orbit-slide">
            <img class="orbit-image" src="{% static 'img/BANNER 4.png' %}" alt="Space">
          </li>
          
          <li class="orbit-slide">
            <img class="orbit-image" src="{% static 'img/BANNER_3.png' %}"  alt="Space">
          </li>
        </ul>
        <nav class="orbit-bullets">
          <button class="is-active" data-slide="0"><span class="show-for-sr">First slide details.</span><span class="show-for-sr">Current Slide</span></button>
          <button data-slide="1"><span class="show-for-sr">Second slide details.</span></button>
          <button data-slide="2"><span class="show-for-sr">Third slide details.</span></button>
          <button data-slide="3"><span class="show-for-sr">Third slide details.</span></button>
          
        </nav>
      </div>
    
  </div>
</div>


<ul class="accordion" data-accordion data-allow-all-closed="true"> 
  
   <li class="accordion-item" data-accordion-item>
    <a href="#deeplink2" class="accordion-title"  ><center> <H5>  CONSULTAR GUIA</H5> </center></a>
    <div class="accordion-content" data-tab-content id="deeplink2">
      <p class="text-center"><iframe src="https://express.firstsource.net.co/tk1/" width="800"></iframe></p>
    </div>
  </li> 
  
</ul>


  <article class="grid-container">
    <div class="grid-x grid-margin-x">
      <div class="medium-7 large-6 cell">
      </div>
    </div>
  
  <div class="">
    <hr>
  </div>
  
  <div class="">
    <p class="lead">Conoce nuestros servicios</p>
  </div>
  
  <div class="grid-x grid-margin-x small-up-1 medium-up-2 large-up-3">
    
    <div class="cell">
      <div class="callout">
        <p><img src="{% static 'img/expresa.png' %}" alt="image of a planet called Pegasi B"></p>
        <p class="lead">Mensajería expresa</p>
        <p class="subheader">Movilización de envíos cuyo peso real o volumérico sea igual o inferior a 5 kg con covertura a nivel nacional.</p>
        <a href="{% url 'home_app:mensajeria-documentos' %}" class="button small expanded hollow">Ver más</a>
      </div>
    </div>
    <div class="cell">
      <div class="callout">
        <p><img src="{% static 'img/paqueteo 1.png' %}" alt="image of a planet called Pegasi B"></p>
        <p class="lead">Cargue paqueteo</p>
        <p class="subheader">Envíos de paquetes y cajas, servicos dedicados y aéreos a nivel nacional cuyo peso real o vulumétrico puede ser mayor a 30 kg.</p>
        <a href="{% url 'home_app:paqueteo' %}" class="button small expanded hollow">Ver más</a>
      </div>
    </div>
    <div class="cell">
      <div class="callout">
        <p><img src="{% static 'img/moto.jpg' %}" alt="image of a planet called Pegasi B"></p>
        <p class="lead">Servicios adicionales</p>
        <p class="subheader">Personal capacitado y eficiente para gestionar los procesos administrativos - logísticos de las empresas a nivel nacional.</p>
        <a href="{% url 'home_app:servicios-adicionales' %}" class="button small expanded hollow">Ver más</a>
      </div>
    </div>

  </div>
  
  </article>

  <article class="grid-container">
    
    <div class="grid-x grid-margin-x">
      <div class="medium-6 cell small-order-2 medium-order-1">
        
        <p ><strong> ¿Quiénes somos? </strong></p>
        <p class="subheader">Somos un operador logístico integral, con amplia experiencia y reconocimiento en servicios de mensajería expresa, mensajería masiva paqueteo, E-commerce, carga masiva y semi masiva.</p>
        <p class="subheader">Nuestro objetivo principal es la satisfacción de nuestros clientes a través de soluciones innovadoras, que permitan prestar un servicio de excelente calidad.</p>
        <p class="subheader">FIRSTSOURCE S.A.S es un operador logístico a nivel nacional que tiene dentro de sus líneas de negocio la Mensajería Expresa, Paqueteo y Carga, Call y Contact 
          Center y E-commerce con alta experiencia y reconocimiento en la prestación de servicios integrales; <br>
          su propósito es la satisfacción de sus clientes a través de soluciones innovadoras y analíticas que permitan prestar un servicio de alta calidad, adaptabilidad y eficiencia. <a href="{% url 'home_app:quienes-somos' %}" ><FONT COLOR="navy">Ver mas... </FONT></a> 
     
          
        </p>
     
      
      </div>
      <div class="medium-6 cell small-order-1 medium-order-2">
        <img class="thumbnail" src="{% static 'img/DSC_0306.JPG' %}">
      </div>
    </div>
    
    

  </article>
  


</div>
  
  {% endblock publico-content %}

letran/templates/publico/politica_sgc.html
{% extends "publico/base_publico.html" %} 

{% load static %}

{% block publico-content %}
<h1>Prueba</h1>


{% endblock publico-content %}